<a href="https://colab.research.google.com/github/sushii-00/MACHINE-LEARNING-A-Z/blob/main/Copy_of_data_preprocessing_tools.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Data Preprocessing Tools

## Importing the libraries

In [ ]:
import numpy as np
import matplotlib.pyplot as plt #matplotlib library contains the pyplot module
import pandas as pd

## Importing the dataset

In [ ]:
#make a variable that will contain the dataset

dataset = pd.read_csv('Data.csv') #read_csv is a function of the library, when you put the name of the data set with the extension. it will read the file and make an array.

#now we need to make: features and the dependent variable vectors (this is usually the last column)

'''
iloc:- 

In the **FIRST part** (i.e., before the comma), 
we need to specify how many **ROWS** do we want to take. 
since we want to take all, we will simply put ':'
since no upper and lower bounds are specified, it is implied that all the rows must be taken.
 
In the **Second part** (i.e., after the comma).,
we need to specify how many **COLUMNS** we want to take.
since we want to take all the columns except for the last one ': -1'
since before :, no upper bound is specified so start from the first column,
but (-1) so go upto the last column but exclude that(Since python always excludes the lower bounds)

'''

X = dataset.iloc[ : , : -1].values 
y = dataset.iloc[ :, -1].values # : gives us a range since we only need one column, we will delete : here
  



In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


## Taking care of missing data

In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#THERE ARE SOME MISSING COLUMNS IN HERE. WE NEED TO TACKLE THEM BEFORE PROCEEDING FURTHER.
#REPLACE THE MISSING DATA WITH THE AVERAGE OF THE WHOLE COLUMN
#(we can take average, mean or even the most frequent value that appears in all rows of the column)
#however, the average is the best method.

In [ ]:
# WE ARE TAKING CARE OF SALARY NOW:
#to perform the operation, we will use thescikit learn library's
#SimpleImputer CLASS

from sklearn.impute import SimpleImputer

#NOW MAKE AN INSTANCE (OBJECT) OF THE CLASS.

imputer = SimpleImputer(missing_values=np.nan, strategy='mean' )

# apply the object to the input features

# fit method, look at the missing values and computes  avg values. 
#the transform function will transform our dataset

#this will only compute the numerical columns, 
#so carefully only fit it to those columns and not to the text columns

imputer.fit(X[ : , 1 : 3])  #only tackling the age and salary cols

X[ : , 1 : 3] = imputer.transform(X[ : , 1 : 3]) # TO MAKE THE CHANGES



In [ ]:
print(X)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


## Encoding categorical data

### Encoding the Independent Variable

In [ ]:
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
print(X)

[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 63777.77777777778]
 ['France' 35.0 58000.0]
 ['Spain' 38.77777777777778 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [ ]:
# to turn categorical columns into numerical data, we use one hot encoding

#we will use 2 classes

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#object for these classes

ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder = 'passthrough')

#fitting and transforming

X = np.array(ct.fit_transform(X))

In [ ]:
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


### Encoding the Dependent Variable

In [ ]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [ ]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


## Splitting the dataset into the Training set and Test set

In [ ]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 1)

In [ ]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [ ]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [ ]:
print(y_test)

[0 1]


## Feature Scaling

We should apply feature scaling after splitting the data, because we musn't work on the test set. That should be completely new information for our model. 

Therefore, Feature scaling before splitting will cause information leakage.

There are two methods
* **Standardisation** :

>X_stand = x - mean(x) / standard_deviation(x)

> all the features come in between -3 and +3 

* **Normalisation**:

>X_norm = x-min(x) / max(x)-min(x)

> all the features come between 0 and 1.


* Normalisation is recommended when most of your features are normally distributed.

* Standardisation works always.
(therefore, always works, therefore, most recommended)


In [ ]:
# standardisation

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()

"""
**Do we apply standardisation to dummy variables? NO.**
because standardisation converts all the values between -3 and +3, 
it will also do the same for dummy variables.
but, (a) they already are in the perfect range and (b) if you implement 
standardisation on those dummy varaibles they will lose their essential 
meaning, cause they were encoded accordingly. So, NO.

"""

X_train[ : , 3 : ] = sc.fit_transform(X_train[ : , 3 : ]) 

#in 3: take all the columns in the end
X_test[ : , 3 : ] = sc.transform(X_test[ : , 3 : ]) 
# we will not fit it again, because then it will be transformed in a different way and will not be congruent with our training set


In [ ]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [ ]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
